#!/usr/bin/env bash
# /usr/local/sbin/runpod-sync.sh — timer every 10 min
# First draft, not yet tested

# Other notes:
# Two things worth knowing
# 
# First, check whether the pod exports its own mapping: run env | grep RUNPOD inside it. If RUNPOD_TCP_PORT_4949 and RUNPOD_PUBLIC_IP are populated (I've confirmed the pattern for port 22 and the 70000 range, but not for arbitrary ports), you can invert this into a proper dyndns registration — the pod POSTs its own mapping to a tiny endpoint on the monitoring host at startup. That's event-driven instead of polled, needs no RunPod API key on the monitoring server, and updates instantly instead of within ten minutes. Nicer, but the polling version above is the one that works regardless.
# 
# Second, tune the alerting for the gap. Between a pod reset and the next sync you'll have up to ten minutes of stale address, which Nagios will read as HOST DOWN. Give the template generous max_check_attempts and retry_interval so the reboot window doesn't page you.

set -euo pipefail

POD_ID="ldl1dxirsim64n"
NODE="gpu-pod-01"
API_KEY="$(< /etc/runpod/api_key)"

json=$(curl -fsS --max-time 20 -X POST \
  -H 'content-type: application/json' \
  "https://api.runpod.io/graphql?api_key=${API_KEY}" \
  -d "{\"query\":\"query { pod(input:{podId:\\\"${POD_ID}\\\"}) { runtime { ports { ip isIpPublic privatePort publicPort type } } } }\"}")

# if the pod is stopped, runtime is null — leave existing config alone
jq -e '.data.pod.runtime.ports' >/dev/null <<<"$json" || exit 0

get() { jq -r --argjson p "$1" \
  '.data.pod.runtime.ports[] | select(.isIpPublic and .privatePort==$p) | .publicPort' <<<"$json"; }

ip=$(jq -r '.data.pod.runtime.ports[] | select(.isIpPublic) | .ip' <<<"$json" | head -1)
munin_port=$(get 4949)
nrpe_port=$(get 5666)
[[ -n "$ip" && -n "$munin_port" && -n "$nrpe_port" ]] || exit 1

tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
# GENERATED by runpod-sync — do not edit
[${NODE}]
    address ${ip}
    port ${munin_port}
    use_node_name yes
EOF
install -C -m 0644 "$tmp" /etc/munin/munin-conf.d/runpod.conf

cat > "$tmp" <<EOF
# GENERATED by runpod-sync — do not edit
define host {
    host_name       ${NODE}
    use             gpu-pod-template
    address         ${ip}
    _NRPE_PORT      ${nrpe_port}
}
EOF
if ! cmp -s "$tmp" /etc/nagios4/conf.d/runpod.cfg; then
    install -m 0644 "$tmp" /etc/nagios4/conf.d/runpod.cfg
    nagios4 -v /etc/nagios4/nagios.cfg >/dev/null && systemctl reload nagios4
fi
